channels:
- conda-forge
dependencies:
- python=3.11.12
- pip<=24.1.2
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
